### PR TITLE
[WIP] Add Checkov as HCL analyzer

### LINKED ISSUE #507: How to add Checkov Tool to Scan Terraform
**What happened**:

TfSec is good for scan terraform code but this tool needs to do `terraform init` first. Run in locally yes we can do that, but if we integrate Horusec on the CI/CD it's hard to do that. So, I look another tool like Checkov (https://github.com/bridgecrewio/checkov) which can scan terraform without `terraform init`. But, when I check into this directory https://github.com/ZupIT/horusec/tree/main/internal/services/formatters/hcl the folder structure is not designed to have multiple tools as mentioned on the docs https://horusec.io/docs/tutorials/how-to-add-tools-using-horusec-engine

Any suggestions?

### PR DESCRIPTION
**Pull request by wibisana-kargo**
**DEPENDS ON**
- https://github.com/ZupIT/horusec/pull/508
- https://github.com/ZupIT/horusec-devkit/pull/61

**- What I did**

Added Checkov as a HCL analyzer, which provides larger coverage than Tfsec. Current implementation ignores `docker` and `secrets` vulnerability, and only shows terraform vulnerabilities. Closes #507 

**- How to verify it**

Run `horusec` with `terraform` enabled, without ignoring `checkov`. This repository https://github.com/bridgecrewio/terragoat can be used to scan on, with known vulnerabilities

**- Description for the changelog**

- Added Checkov as HCL analyzer

### CODE REVIEW

**Comment by wiliansilvazup** [comment]
all pull requests were merged!

We've also updated the base for develop just to push all content at once to the main branch, so check for conflicts so we can move on

**Comment by wiliansilvazup** [comment]
If possible also add an example case where vulnerabilities can be found inside the folder [/examples/hcl](https://github.com/ZupIT/horusec/tree/develop/examples/hcl)

**Comment by wibisana-kargo** [comment]
Hi @wiliansilvazup,

I'm currently having a problem with fixing the deployment. Since the code for `Trivy` has been merged here, but has not been added to the `horusec-devkit` release, this version cannot be deployed properly. Can you help me mend this issue?

**Comment by wiliansilvazup** [comment]
> Hi @wiliansilvazup,
> 
> I'm currently having a problem with fixing the deployment. Since the code for `Trivy` has been merged into the development branch here, but has not been added to the `horusec-devkit` release, this version cannot be deployed properly. Can you help me mend this issue?

I just made the necessary updates to horusec-devkit, you can update it to the latest version v1.0.11 🚀

**Comment by wibisana-kargo** [comment]
I've updated the code to fix some issues found after running the finished code. Other than that, I updated the dependencies and ran `go mod tidy` to remove unnecessary dependencies.

Also, `Checkov` will show vulnerabilities while scanning the example provided in [examples/hcl/example1](https://github.com/ZupIT/horusec/tree/develop/examples/hcl/example1)

 Hope this can be merged soon

**Comment by wiliansilvazup** [comment]
tnks for updates @wibisana-kargo, for merge your pull request is necessary fix some problems found in review. For fix this problems horusec provides some commands for help you, see below:

* `make coverage`
* `make lint`
* `make test`

image

**Comment by wibisana-kargo** [comment]
I've updated the code to align with the checks. Is there a way for me to see the results of those or is that privated?

**Comment by wiliansilvazup** [comment]
> I've updated the code to align with the checks. Is there a way for me to see the results of those or are they privated?

Into your branch of the your fork, you can see github actions running and your results :)

I'll pass and the next step is merge this PR 🚀 

image

**Comment by wiliansilvazup** [comment]
Tnks for your contribution  @wibisana-kargo 🚀

**Pull request merged**
