### PR TITLE
chore:workflow - Added new workflow to validate release workflows

### PR DESCRIPTION
**Pull request by wiliansilvazup**
In this commit was added a new workflow to check if the when dispatch
alpha, beta, rc, release final any problem was detected in
developement time.

Signed-off-by: Wilian Gabriel <wilian.silva@zup.com.br>

### CODE REVIEW

**Comment by iancardosozup** [comment]
why create another workflow instead of using the [Build](https://github.com/ZupIT/horusec/blob/main/.github/workflows/build.yaml) one ?

**Comment by wiliansilvazup** [comment]
> why create another workflow instead of changing the [Build](https://github.com/ZupIT/horusec/blob/main/.github/workflows/build.yaml) one ?

In this context the build workflow is not enough, because goreleaser build the project using some flags and params differents of the normal build, then I create this workflow to validate before run alpha all release process it's ok

**Comment by iancardosozup** [comment]
i understand, with this new workflow i don't see any usage for the existing build workflow, we could just replace it to your new version and we'll always check if the release process would be ok. Since there is no release i see this workflow as build binaries and build docker images, is a improvement to the current build workflow

**Comment by nathanmartinszup** [comment]
I agree with @iancardosozup, I see no need to maintain both workflows.

Another point, as we are only going to build the cli and images, is it necessary to docker login, create tag, import gpg key? Can't we just run the go release directly?

**Review by iancardosozup — APPROVED** [review]

**Review by nathanmartinszup — APPROVED** [review]

**Review by matheusalcantarazup — APPROVED** [review]

**Pull request merged**
